# Generated by Django 2.2.12 on 2022-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=71)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=50)),
            ],
        ),
    ]
