# Generated by Django 2.2.12 on 2022-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='d45',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('effectif', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
