# Generated by Django 2.2.12 on 2022-05-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_etudiants', '0002_auto_20220530_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=100)),
                ('matiere1', models.PositiveIntegerField()),
                ('matiere2', models.PositiveIntegerField()),
                ('matiere3', models.PositiveIntegerField()),
                ('matiere4', models.PositiveIntegerField()),
                ('matiere5', models.PositiveIntegerField()),
                ('matiere6', models.PositiveIntegerField()),
            ],
        ),
    ]
